config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'
  get 'pages/contact'
  get 'pages/admin'
  get 'pages/about'
  root 'pages#home'
  resources :links
  resources :campaigns
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 
  
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base

end

app/models/link.rb
class Link < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

	respond_to :json

	def index
		@campaigns = Campaign.all.order("created_at DESC")

		if user_signed_in?

		else
			redirect_to "/users/sign_in"
		end
		
	end

	def new
		@campaign = Campaign.new
	end

	def create
		@campaign = Campaign.new(campaign_params)
		@campaign.save
	end

	def show
		@campaign = Campaign.find(params[:id])
	end

	def destroy
		@campaign = Campaign.find(params[:id])
		@campaign.destroy
		redirect_to "/campaigns"
	end

	private

	def campaign_params
		params.require(:campaign).permit(:title, :name, :link, :description, :date, :owner)
	end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
	
	respond_to :json

	def index
		@links = Link.all.order("created_at DESC")
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(link_params)
		@link.save
	end

	def show
		@campaign = Campaign.new
		@link = Link.find(params[:id])
	end

	def destroy
		@link = Link.find(params[:id])
		@link.destroy

		redirect_to "/links"
	end
	
	private

	def link_params
		params.require(:link).permit(:title, :name, :description, :link, :place)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	
  end

  def admin
  	current_user.update_attribute :admin, true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/campaigns/index.html.erb
<html>
	<head>
		
	</head>
	<body>
		<% if current_user.try(:email) == "sbhenrichs@gmail.com" || current_user.try(:email) == "camblackwell2@gmail.com" %>
			<h1 class="strong">Campaigns</h1>
		<% else %>
			<h1 class="strong">Your Campaigns</h1>
			<h4 class="text-center">(<%= current_user.try(:email) %>)</h4>
		<% end %>
		<% @campaigns.each do |campaign| %>
		<% if campaign.owner == current_user.try(:email) || current_user.try(:email) == "sbhenrichs@gmail.com" || current_user.try(:email) == "camblackwell2@gmail.com" %>
			<div class="offer">
				<h2 class="text-center blue"><%= campaign.name %></h2>
				<br>
				<%= campaign.description %>
				<br>
				<%= campaign.owner %>
				<br>
				<%= link_to "View", campaign, class: "link-black offer-link" %>
			</div>
		<% else %>
		<% end %>
		<% end %>
		<div class="bottom">
			<a href="/users/edit" class="btn btn-info">Edit Profile</a>
		</div>

	</body>
</html>

app/views/campaigns/show.html.erb
<html>
	<head>
		
	</head>
	<body>
		<h1 class="strong"><%= @campaign.name %></h1>
		<h4>Started: <%= @campaign.date %></h4>
		<br>
		<h4><span>Your Email: </span><%= @campaign.owner %></h4>
		<br>
		<p>Description: <%= @campaign.description %></p>
		<%= link_to "End Campaign", campaign_path(@campaign), class: "link-black",method: :delete, data: { confirm: "Once you end your campaign, you will be paid in full. Are you sure you want to do this?" }, class: "btn btn-info space" %>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Force</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 	<div class="nav">
 		<div class="logo">
 			<span class="brand">
 				blog/force<i id="beta">beta</i>
 			</span>
 		</div>
 		<% if user_signed_in? %>
			<% if current_user.try(:email) == "sbhenrichs@gmail.com" || current_user.try(:email)== "camblackwell2@gmail.com" %>
				<div class="links-box">
		 			<a href="/links" class="link">Offers</a>
		 			<a href="/campaigns" class="link">Campaigns</a>
		 			<a href="/links/new" class="link">New Link</a>
		 			<a href="/users/sign_in" class="link">Log In</a>
		 			<a href="/users/sign_up" class="link">Sign Up</a>
		 			<span class="link"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></span>
 				</div>
			<% else %>
				<div class="links-box">
					<a href="/links" class="link">Offers</a>
					<a href="/campaigns" class="link"><%= current_user.try(:email) %></a>
					<a href="/pages/contact" class="link">Contact Us</a>
					<span class="link"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
				</div>
			<% end %>
 		<% else %>
			<div class="links-box">
				<a href="/pages/home" class="link">Home</a>
				<a href="/pages/about" class="link">About</a>
				<a href="/pages/contact" class="link">Contact Us</a>
				<a href="/users/sign_in" class="link">Log In</a><span>/</span>
				<a href="/users/sign_up" class="">Sign Up</a>
			</div>
 		<% end %>
 		
 	</div>
 	
 	<div class="body">

<%= yield %>
	</div>
</body>
</html>

app/views/links/index.html.erb
<html>
	<head>
		
	</head>
	<body>
			<h1 class="strong">Offers</h1>
			
			<div class="tighten">
			<% if user_signed_in? %>
			<br>
			<% @links.each do |link| %>
				<% if link.place == 2 %>
					<% if Link.where(title: link.title).count >= 2 %>					
					<% else %>
						<%= link.title %>
						<br>
						<%= link.name %>
						<br>
						<%= link.description %>
						<br>
						<%= link.place %>
						<br>
						<a href="<%= link.link %>" class="link-black"><%= link.link %></a>
						<br>
						<%= link_to "View", link, class: "link-black" %>
						<br>
						<br>
					<% end %>
				<% else %>
				<% if link.place == 3 %>
					<% if Link.where(title: link.title).count >= 3 %>
					<% else %>
						<%= link.title %>
						<br>
						<%= link.name %>
						<br>
						<%= link.description %>
						<br>
						<%= link.place %>
						<br>
						<a href="<%= link.link %>" class="link-black"><%= link.link %></a>
						<br>
						<%= link_to "View", link, class: "link-black" %>
						<br>
						<br>
					<% end %>
				<% else %>
				<div class="offerl">
					<h3 class="blue"><%= link.title %></h3>
					<%= link.description %>
					<br>
					<%= link_to "More Info", link, class: "offer-link link-black" %>
				</div>			
			<% end %>
			<% end %>
			<% end %>
			<% else %>
			<h2 id="notsignedin">To view our offers, please <a href="/users/sign_in" class="link-black">sign in.</a></h2>
			<% end %>

		</div>
	</body>
</html>

app/views/links/new.html.erb
<html>
	<head>
		
	</head>
	<body>
		<% if current_user.try(:email) == "sbhenrichs@gmail.com" || current_user.try(:email) == "camblackwell2@gmail.com" %>
			<h1 class="strong">New Link</h1>
			<%= form_for @link do |f| %>
				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :name %>
					<%= f.text_field :name, class: "form-control" %>
				</div>
				<div class="form-group">
					<%= f.label :description %>
					<%= f.text_area :description, class: "form-control" %>
				</div>
				<div class="form-group">
				<%= f.label :link %>
				<%= f.url_field :link, class: "form-control" %>
				</div>
				<div class="form-group">
				<%= f.label :place %>
				<%= f.number_field :place, class: "form-control" %>
				</div>
				<%= f.submit :"Create Link", class: "btn btn-info" %>
			<% end %>
		<% end %>

	</body>
</html>

app/views/links/show.html.erb
<html>
	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
		<script type="text/javascript" src="link.js"></script>
	</head>
	<body>
		<h1 class="strong"><%= @link.name %></h1>
		<br>

			<div class="description lighter"><%= @link.description %></div>
			<br>
			<a href="<%= @link.link %>" class="link-black offer-link">View Product on Amazon</a>
			<br>
			<% if current_user.try(:email) == "sbhenrichs@gmail.com" || current_user.try(:email) == "camblackwell2@gmail.com"%>
			<%= link_to "Delete", link_path(@link), method: :delete, data: { confirm: "Are you sure?" }, class: "offer-link link-black" %>
			<% end %>
			<br>
			<br>
			<br>
		
		<%= form_for @link, method: :delete, class: "link" do |f| %>
			<%= f.submit :"Delete Link", class: "btn btn-info" %>
		<% end %>
		<br>
		<%= form_for :campaign, url: campaigns_path, class: "campaign" do |x| %>
			<%= x.hidden_field :title, value: @link.title %>
			<%= x.hidden_field :name, value: @link.name %>
			<%= x.hidden_field :link, value: @link.link %>
			<%= x.hidden_field :description, value: @link.description %>
			<%= x.hidden_field :owner, value: current_user.try(:email) %>
			<%= x.hidden_field :date, value: Date.today.to_s %>
			<%= x.submit :"Start Campaign", class: "btn btn-info" %>
		<% end %>

	</body>
</html>

app/views/pages/about.html.erb
<html>
	<head>
		
	</head>
	<body>
		<h1 class="strong">About</h1>
	</body>
</html>

app/views/pages/contact.html.erb
<html>
	<head>
		
	</head>
		<h1 class="strong">Contact Us</h1>
</html>

app/views/pages/home.html.erb
<html>
	<head>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
		<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
		<script type="text/javascript" src="custom.js"></script>
	</head>
	<body>
			
	</body>
</html>